version: '3.8'

services:
  php:
    image: php:7.4-fpm
    container_name: php
    volumes:
      - ./app:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - php-recipes-api_mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./app/public:/var/www/html/public
    networks:
      - php-recipes-api_mynetwork

  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_DB: hellofresh
      POSTGRES_USER: hellofresh
      POSTGRES_PASSWORD: hellofresh
    ports:
      - "5432:5432"
    networks:
      - php-recipes-api_mynetwork

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - php-recipes-api_mynetwork

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - php-recipes-api_mynetwork

networks:
  php-recipes-api_mynetwork:
    driver: bridge
