version: '3.1'

services:
  php:
    image: php:7.4-fpm
    container_name: php
    volumes:
      - ./app:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - mynetwork

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
       - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork

  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_DB: hellofresh
      POSTGRES_USER: hellofresh
      POSTGRES_PASSWORD: hellofresh
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
